# Generated by Django 5.0.6 on 2024-06-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ischeck', models.BooleanField(default=True, verbose_name='it is an checkbox')),
            ],
        ),
    ]
