# Generated by Django 5.0.6 on 2024-06-20 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 20, 13, 6, 52, 665947)),
        ),
        migrations.AddField(
            model_name='student',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 13, 6, 52, 665947)),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=2, max_length=30, verbose_name='enter your name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
