# Generated by Django 5.0.6 on 2024-06-20 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_date_student_date1_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 20, 13, 10, 29, 738219)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 13, 10, 29, 738219)),
        ),
    ]
