# Generated by Django 5.0.6 on 2024-06-20 10:18

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_surname_alter_student_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AddField(
            model_name='student',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='decimal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='url',
            field=models.URLField(default='www.facebook.com'),
        ),
        migrations.AddField(
            model_name='student',
            name='var',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 20, 16, 3, 28, 912754)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 16, 3, 28, 912754)),
        ),
    ]
