# Generated by Django 5.0.6 on 2024-06-20 10:29

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_surname_student_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 20, 16, 14, 52, 906753)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 16, 14, 52, 906753)),
        ),
    ]
